service: interest-mailer

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

functions:
  interest-mailer:
    handler: dist/lambda/src/mailer.handler
    package:
      excludeDevDependencies: true
    events:
      - http:
          path: sendMail
          method: POST
          cors: true
