name: RAD-RIF CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install and lint
        working-directory: ./frontend
        run: |
            yarn install |
            yarn lint
        env:
          CI: true
      - name: Run TypeScript Compiler option
        working-directory: ./frontend
        uses: icrawl/action-tsc@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          job-name: TypeScript Compiler
